### ISSUE TITLE
Incompitable with 4.5.3

### ISSUE THREAD

**Issue by stardnce** [dddfault/NativeEnhancer-FE-DX10#1]
Can't compile on 4.5.3 if using macros.fxh from that release. If using your macros.fxh, crosire shaders break.

**Comment by dddfault** [comment]
Can you tell me which crosire shaders that break while using this release macros.fxh?

**Comment by dddfault** [comment]
https://github.com/dddfault/NativeEnhancer-FE-DX10/commit/53f653b1a9169208fa3dcfba6d9470a50219dd8b

**Comment by dddfault** [comment]
Issue closed due the lack of crash log, evidence, nor information about the incompability.
This shader already tested on new ReShade version with updated Macros.fxh file.
