### ISSUE TITLE
error X4509

### ISSUE THREAD

**Issue by tametoarie** [dddfault/NativeEnhancer-FE-DX10#2]
![Screenshot_1](https://user-images.githubusercontent.com/62075556/76453244-8ea31580-63e3-11ea-92f2-6dcdaffb0ab7.png)

Hello, please tell me how to fix it?

**Comment by dddfault** [comment]
which API did you use while using the shader? this shader only works on DX10+ API since there is limit issue on DX9 / OpenGL API
