### ISSUE TITLE
I want AUTO-ISO added!!!!!

### ISSUE THREAD

**Issue by ymtymt** [dddfault/NativeEnhancer-FE-DX10#3]
I have a request for a new feature on this wonderful shader!
I would like to see the addition of AUTOISO for the camera in regards to film grain.
AUTOISO is a feature that sets the ISO sensitivity to, say, 200 when the screen is bright, and sets the maximum ISO sensitivity to 10,000 when the screen is dark.

This would allow us to reproduce the phenomenon of less noise when the screen is bright and more noise when the screen is dark.

This is the same function as AUTOISO on a camera.

Sorry for my bad English.

**Comment by dddfault** [comment]
Sorry, unfortunately I can't do complex stuff like that. That feature is already exist on way better film simulation shader, like TreyM's Film Workshop. Maybe you wanna try that instead of this one.
